version: '2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes_from:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    links:
      - app
      - php
      - mysql

  app:
    command: "true"
    image: alpine:3.6
    volumes:
      - ./:/var/www/app
    links:
      - mysql
    networks:
      - app-network

  php:
    build: docker/php
    expose:
      - 9000
    volumes:
      - ./composer-cache:/composer/cache
    volumes_from:
      - app
    networks:
      - app-network
    links:
      - mysql
      - redis

  redis:
    image: redis:alpine
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    networks:
      - app-network

  mysql:
    image: mysql:latest
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: forum
      MYSQL_USER: forum
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - app-network

  minio:
    image: minio/minio
    command: server /export
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - ./minio/export:/export
      - ./minio/config:/root/.minio
    ports:
      - 9005:9000
    networks:
      - app-network

volumes:
  composer-cache:
    driver: local

networks:
  app-network:
    driver: bridge
